package learning

import (
	"strings"
	"testing"

	"github.com/UnicoLab/slmcode/pkg/memory"
	"github.com/UnicoLab/slmcode/pkg/plan"
)

// newFacts opens an in-process fact store (no directory ⇒ no disk).
func newFacts(t *testing.T) *memory.Facts {
	t.Helper()
	store, err := memory.Open("", t.TempDir())
	if err != nil {
		t.Fatalf("open memory: %v", err)
	}
	t.Cleanup(func() { _ = store.Close() })
	return store.Semantic()
}

func TestFactFromLessonSetsKindSourcesAndConfidence(t *testing.T) {
	cases := []struct {
		lessonKind string
		wantKind   memory.FactKind
	}{
		{"failure", memory.FactGotcha},
		{"convention", memory.FactConvention},
		{"success", memory.FactConvention},
		{"", memory.FactConvention},
		{"something-nobody-defined", memory.FactConvention},
	}
	for _, tc := range cases {
		f, ok := FactFromLesson(Lesson{
			TaskID: "T3", Kind: tc.lessonKind,
			Text: "Fixtures live under testdata and are regenerated by make gen",
			At:   "2026-08-24T10:00:00Z",
		}, "run-42")
		if !ok {
			t.Fatalf("kind %q: conversion refused", tc.lessonKind)
		}
		if f.Kind != tc.wantKind {
			t.Errorf("kind %q → %q, want %q", tc.lessonKind, f.Kind, tc.wantKind)
		}
		// Provenance must be queryable from the typed store, not only readable
		// in MEMORY.md.
		if len(f.Sources) != 2 || f.Sources[0] != "T3" || f.Sources[1] != "run-42" {
			t.Errorf("kind %q sources = %v, want [T3 run-42]", tc.lessonKind, f.Sources)
		}
		if !strings.HasPrefix(f.Subject, lessonSubjectPrefix) {
			t.Errorf("kind %q subject %q is not namespaced", tc.lessonKind, f.Subject)
		}
	}

	if _, ok := FactFromLesson(Lesson{TaskID: "T1", Kind: "failure", Text: "   "}, "run-1"); ok {
		t.Error("an empty lesson must not become a fact")
	}

	// Confidence is the store's Beta(1,1) posterior, not something the bridge
	// invents: one sighting is a hint (0.67), not a law (1.0).
	facts := newFacts(t)
	if n := RecordFacts(facts, []Lesson{{
		TaskID: "T3", Kind: "failure", Text: "qa_gate smoke command must run before finalizing",
	}}, "run-42"); n != 1 {
		t.Fatalf("recorded %d facts, want 1", n)
	}
	stored := facts.OfKind(memory.FactGotcha)
	if len(stored) != 1 {
		t.Fatalf("stored %d gotchas, want 1", len(stored))
	}
	if got := stored[0].Confidence; got < 0.66 || got > 0.68 {
		t.Errorf("confidence = %.3f, want Beta(1,1) posterior 0.667", got)
	}
	if stored[0].Support != 1 {
		t.Errorf("support = %d, want 1", stored[0].Support)
	}

	// A repeat of the same claim is confirmation, so confidence must rise.
	RecordFacts(facts, []Lesson{{
		TaskID: "T9", Kind: "failure", Text: "qa_gate smoke command must run before finalizing",
	}}, "run-43")
	stored = facts.OfKind(memory.FactGotcha)
	if stored[0].Support != 2 || stored[0].Confidence <= 0.67 {
		t.Errorf("a confirmed lesson did not gain confidence: support=%d conf=%.3f",
			stored[0].Support, stored[0].Confidence)
	}
	if len(stored[0].Sources) != 4 {
		t.Errorf("sources = %v, want both runs and both tasks", stored[0].Sources)
	}
}

// TestContradictingLessonsConverge proves the whole point of routing prose into
// the typed store: a lesson the project has outgrown can now be outvoted. In
// flat MEMORY.md the two bullets below would coexist forever, both injected,
// contradicting each other in the prompt.
func TestContradictingLessonsConverge(t *testing.T) {
	facts := newFacts(t)
	const (
		oldClaim = "qa_gate smoke command must run before every single edit"
		newClaim = "qa_gate smoke command must run once at the end of a wave"
	)
	RecordFacts(facts, []Lesson{{TaskID: "T1", Kind: "convention", Text: oldClaim}}, "run-1")

	got, ok := facts.Get(memory.FactConvention, lessonSubjectPrefix+lessonSubject(oldClaim))
	if !ok {
		t.Fatalf("first lesson not stored; facts=%+v", facts.All())
	}
	if got.Text != oldClaim {
		t.Fatalf("stored text = %q, want %q", got.Text, oldClaim)
	}
	if lessonSubject(oldClaim) != lessonSubject(newClaim) {
		t.Fatalf("test premise broken: rival claims must share a subject (%q vs %q)",
			lessonSubject(oldClaim), lessonSubject(newClaim))
	}

	// One rival sighting contradicts but does not yet win: a single observation
	// must not be able to overwrite an established claim.
	RecordFacts(facts, []Lesson{{TaskID: "T2", Kind: "convention", Text: newClaim}}, "run-2")
	got, _ = facts.Get(memory.FactConvention, lessonSubjectPrefix+lessonSubject(oldClaim))
	if got.Text != oldClaim {
		t.Errorf("one contradiction flipped the fact; text = %q", got.Text)
	}
	if got.Contradict != 1 {
		t.Errorf("contradiction not counted: %+v", got)
	}
	if got.Confidence >= 0.67 {
		t.Errorf("confidence did not fall on contradiction: %.3f", got.Confidence)
	}

	// Once the rival claim outweighs the older one, the store supersedes it and
	// resets the counters — that is how a fact decays when the project moves.
	RecordFacts(facts, []Lesson{{TaskID: "T3", Kind: "convention", Text: newClaim}}, "run-3")
	got, _ = facts.Get(memory.FactConvention, lessonSubjectPrefix+lessonSubject(oldClaim))
	if got.Text != newClaim {
		t.Fatalf("store did not converge on the newer claim; text = %q", got.Text)
	}
	if got.Contradict != 0 || got.Support != 1 {
		t.Errorf("counters not reset after supersession: %+v", got)
	}

	// One subject, not two: the prompt can never carry both claims at once.
	if n := len(facts.OfKind(memory.FactConvention)); n != 1 {
		t.Errorf("rival claims stored as %d facts, want 1", n)
	}
}

// TestLessonSubjectIgnoresPerRunTaskIDs: task ids look stable but are per-run,
// so a subject built from them would both split one recurring claim across
// every run that made it and collide two unrelated claims that were task 1.
func TestLessonSubjectIgnoresPerRunTaskIDs(t *testing.T) {
	a := lessonSubject("Avoid repeating T2 failure: missing import in pkg/graph")
	b := lessonSubject("Avoid repeating T17 failure: missing import in pkg/graph")
	if a != b {
		t.Errorf("task ids leaked into the subject: %q vs %q", a, b)
	}
	if strings.Contains(a, "t2") || strings.Contains(a, "t17") {
		t.Errorf("subject %q still carries a task id", a)
	}
	if lessonSubject("qa_gate is red") == lessonSubject("max_parallel is high") {
		t.Error("unrelated lessons collapsed onto one subject")
	}
	// Underscored identifiers must survive whole: they are the words that
	// actually distinguish one harness lesson from another.
	if !strings.Contains(lessonSubject("qa_gate keeps failing"), "qa_gate") {
		t.Errorf("qa_gate was split apart: %q", lessonSubject("qa_gate keeps failing"))
	}
}

// TestExtractedLessonsReachTheFactStore walks the real path: a finished board
// task → Extract → Markdown mirror → typed facts.
func TestExtractedLessonsReachTheFactStore(t *testing.T) {
	blocked := plan.Task{ID: "T4", Column: plan.ColBlocked, Error: "import cycle between pkg/a and pkg/b"}
	blocked.Normalize()
	lessons := Extract(blocked)
	if len(lessons) == 0 {
		t.Fatal("expected a failure lesson")
	}

	facts := newFacts(t)
	if n := RecordFacts(facts, lessons, "run-9"); n != len(lessons) {
		t.Fatalf("recorded %d of %d lessons", n, len(lessons))
	}
	found := false
	for _, f := range facts.All() {
		if strings.Contains(f.Text, "import cycle") {
			found = true
			if f.Kind != memory.FactGotcha {
				t.Errorf("a failure lesson landed in %q, want gotcha", f.Kind)
			}
		}
	}
	if !found {
		t.Fatalf("lesson never reached the fact store: %+v", facts.All())
	}

	// The Markdown route must reach the same place, since half the lessons in a
	// run arrive as prose from the distiller rather than as a []Lesson.
	md := RenderMarkdown(lessons)
	if n := LessonsFromMarkdown(facts, md, "run-10"); n != len(lessons) {
		t.Errorf("markdown route recorded %d of %d lessons", n, len(lessons))
	}

	// nil store must be a no-op, not a panic: `--no-evolve` is a supported mode.
	if n := RecordFacts(nil, lessons, "run-11"); n != 0 {
		t.Errorf("nil store recorded %d facts", n)
	}
}
