package learning

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestAppendReadGlobalMemoryUsesUserLevelPath(t *testing.T) {
	home := t.TempDir()
	t.Setenv("HOME", home)
	t.Setenv("XDG_CONFIG_HOME", "")

	if err := AppendGlobalMemory("Wave lessons", "- Avoid repeating timeout after context deadline exceeded"); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(home, ".slmcode", "MEMORY.md")
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "SLMCode Global Memory") {
		t.Fatalf("missing global memory header:\n%s", data)
	}
	read := ReadGlobalMemory()
	if !strings.Contains(read, "context deadline exceeded") {
		t.Fatalf("global memory not readable:\n%s", read)
	}
}

func TestRecentAdaptiveMemoryMergesGlobalAndProjectSignals(t *testing.T) {
	project := "- project memory: qa_gate failed, fix smoke first\n"
	global := "- global memory: timeout after context deadline exceeded; lower max_parallel\n"

	got := RecentAdaptiveMemory(project, global, 1000)
	if !strings.Contains(got, "global memory") {
		t.Fatalf("missing global signal:\n%s", got)
	}
	if !strings.Contains(got, "project memory") {
		t.Fatalf("missing project signal:\n%s", got)
	}
	if !strings.Contains(got, "timeout") || !strings.Contains(got, "qa_gate") {
		t.Fatalf("lesson text was not carried through verbatim:\n%s", got)
	}
}

// keywordGateWords is the eleven-substring allowlist that used to decide, on
// the ONLY path from a stored lesson to a future prompt, whether that lesson
// survived. It is kept here purely so the tests below can assert that NONE of
// them appear in the lessons they push through — i.e. that the gate is gone.
var keywordGateWords = []string{
	"timeout", "timed out", "deadline", "max_parallel", "contention",
	"smoke", "qa_gate", "acceptance", "placeholder", "stub", "max retries",
}

func containsAnyGateWord(s string) string {
	lower := strings.ToLower(s)
	for _, w := range keywordGateWords {
		if strings.Contains(lower, w) {
			return w
		}
	}
	return ""
}

// TestLessonWithoutKeywordGateWordsStillReachesThePrompt is THE regression for
// the defect this change exists to fix.
//
// appendAdaptiveLines used to drop any line that did not contain one of eleven
// hardcoded substrings. Every lesson below is real, useful, and contains none
// of them — an import cycle, a flaky fixture, a naming convention, a migration
// order. Under the old gate all four were written to disk and then silently
// discarded on their way to the prompt, so the harness could never learn from
// any failure mode nobody had thought to hardcode. They must now all survive.
func TestLessonWithoutKeywordGateWordsStillReachesThePrompt(t *testing.T) {
	lessons := []string{
		"Import cycle: pkg/graph must not import pkg/orchestrator",
		"The Postgres fixture is flaky unless the container is warmed first",
		"Exported identifiers in this repo never abbreviate: use Configuration",
		"Run migrations before seeding or the foreign keys blow up",
	}
	project := ""
	for _, l := range lessons {
		if w := containsAnyGateWord(l); w != "" {
			t.Fatalf("test premise broken: %q contains the old gate word %q", l, w)
		}
		project += "- ⚠ " + l + "\n"
	}

	// Unconditioned (no query): the deterministic recency fallback.
	got := RecentAdaptiveMemory(project, "", 4000)
	for _, l := range lessons {
		if !strings.Contains(got, l) {
			t.Errorf("keyword gate still filtering (unconditioned) — lost %q:\n%s", l, got)
		}
	}

	// Task-conditioned: the relevant lesson must lead, and the rest must still
	// be there. Ordering by relevance is the improvement; dropping lessons that
	// merely fail to match is the bug we are fixing, not a feature to keep.
	got = RecentAdaptiveMemoryFor("fix the import cycle in pkg/graph", project, "", 4000)
	for _, l := range lessons {
		if !strings.Contains(got, l) {
			t.Errorf("keyword gate still filtering (conditioned) — lost %q:\n%s", l, got)
		}
	}
	first := strings.SplitN(strings.TrimSpace(got), "\n", 2)[0]
	if !strings.Contains(first, "Import cycle") {
		t.Errorf("query-relevant lesson did not lead the block; first line = %q\n%s", first, got)
	}
}

// TestAdaptiveMemoryRanksRelevantLessonsFirst checks the positive half: given a
// task, the lesson about that task outranks louder but unrelated ones.
func TestAdaptiveMemoryRanksRelevantLessonsFirst(t *testing.T) {
	project := "- ⚙ Retry the HTTP client with exponential backoff on 429\n" +
		"- ⚠ The Kafka consumer needs an explicit group id\n" +
		"- ⚙ Protobuf schemas live in api/proto and are generated by make gen\n"

	got := RecentAdaptiveMemoryFor("regenerate the protobuf schemas", project, "", 4000)
	first := strings.SplitN(strings.TrimSpace(got), "\n", 2)[0]
	if !strings.Contains(first, "Protobuf") {
		t.Errorf("relevance ranking did not lead with the protobuf lesson:\n%s", got)
	}

	// A query nothing matches must not empty the block: an unmatched lesson is
	// still a lesson, and returning nothing would be a worse regression than
	// returning the recent ones.
	got = RecentAdaptiveMemoryFor("unrelated zzz qqq", project, "", 4000)
	if strings.TrimSpace(got) == "" {
		t.Error("a non-matching query emptied the adaptive block")
	}
}

// TestAdaptiveMemoryRespectsByteAndLineBudgets: relevance changed, budgets did
// not. A prompt budget blown by a memory block is a run that dies of context
// overflow instead of learning anything.
func TestAdaptiveMemoryRespectsByteAndLineBudgets(t *testing.T) {
	var project strings.Builder
	for i := 0; i < 60; i++ {
		fmt.Fprintf(&project, "- ⚙ Lesson number %d about the widget subsystem and its many parts\n", i)
	}
	for _, query := range []string{"", "widget subsystem parts"} {
		for _, budget := range []int{80, 300, 1600} {
			got := RecentAdaptiveMemoryFor(query, project.String(), "", budget)
			if len(got) > budget {
				t.Errorf("query=%q budget=%d: emitted %d bytes:\n%s", query, budget, len(got), got)
			}
			if n := len(strings.Split(strings.TrimSpace(got), "\n")); got != "" && n > maxAdaptiveLines {
				t.Errorf("query=%q budget=%d: emitted %d lines, cap is %d", query, budget, n, maxAdaptiveLines)
			}
		}
	}
}
