package memory

import (
	"strings"
	"testing"
	"time"
)

func TestRankTextSharesTheEpisodeScorer(t *testing.T) {
	cands := []TextCandidate{
		{Text: "the kafka consumer needs an explicit group id"},
		{Text: "protobuf schemas live in api/proto and are generated by make gen"},
		{Text: "retry the http client with exponential backoff"},
	}
	hits := RankText(Query{Text: "regenerate the protobuf schemas in api/proto"}, cands, 0)
	if len(hits) == 0 {
		t.Fatal("no match for an obviously matching query")
	}
	if hits[0].Index != 1 {
		t.Errorf("best match = %d (%q), want 1", hits[0].Index, cands[hits[0].Index].Text)
	}
	// The relative floor and the coverage gate must still do their job: one
	// strong hit does not drag in the other two for company.
	if len(hits) > 1 {
		t.Errorf("weak matches survived the relative floor: %+v", hits)
	}

	if got := RankText(Query{}, cands, 0); got != nil {
		t.Errorf("a query with no terms must rank nothing, got %+v", got)
	}
	if got := RankText(Query{Text: "kafka"}, nil, 0); got != nil {
		t.Errorf("no candidates must rank nothing, got %+v", got)
	}
	if got := RankText(Query{Text: "zzzq qqzz"}, cands, 0); got != nil {
		t.Errorf("a query matching nothing must rank nothing, got %+v", got)
	}
}

func TestRankTextRespectsRecencyAndSuccess(t *testing.T) {
	now := time.Now()
	same := "protobuf schemas in api/proto"
	hits := RankText(Query{Text: same}, []TextCandidate{
		{Text: same, At: now.Add(-365 * 24 * time.Hour)},
		{Text: same, At: now},
	}, 0)
	if len(hits) == 0 || hits[0].Index != 1 {
		t.Errorf("recency decay not applied: %+v", hits)
	}

	hits = RankText(Query{Text: same}, []TextCandidate{
		{Text: same},
		{Text: same, Success: true},
	}, 0)
	if len(hits) == 0 || hits[0].Index != 1 {
		t.Errorf("success boost not applied: %+v", hits)
	}
}

// seedFactsForRender fills a store with seven equally-confident "file" facts on
// a controlled clock, oldest first. Ranking breaks the confidence tie on
// recency, so the oldest — the one fact a caller working on authentication
// actually wants — falls outside the per-kind cap of 6 and is invisible to the
// unconditioned render.
func seedFactsForRender(t *testing.T) *Facts {
	t.Helper()
	clock := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	f := openFacts("", 0, func() time.Time { return clock }, nil)
	observe := func(fact Fact) {
		f.Observe(fact)
		clock = clock.Add(time.Hour)
	}
	observe(Fact{
		Kind:    FactFile,
		Subject: "pkg/auth/token.go",
		Text:    "`pkg/auth/token.go` holds the token refresh logic",
	})
	for _, p := range []string{
		"pkg/render/a.go", "pkg/render/b.go", "pkg/render/c.go",
		"pkg/render/d.go", "pkg/render/e.go", "pkg/render/f.go",
	} {
		observe(Fact{Kind: FactFile, Subject: p, Text: "`" + p + "` changed in 3 recent runs"})
	}
	return f
}

// TestRenderForPrefersFactsRelevantToTheQuery is the positive half of making
// semantic memory query-conditioned: Render used to dump the top six facts per
// kind regardless of what the current task was about, so the one fact that
// mattered could be crowded out by six that did not.
func TestRenderForPrefersFactsRelevantToTheQuery(t *testing.T) {
	f := seedFactsForRender(t)

	plain := f.Render(400)
	if strings.Contains(plain, "pkg/auth/token.go") {
		t.Fatalf("test premise broken: the auth fact is inside the unconditioned cap:\n%s", plain)
	}

	cond := f.RenderFor(Query{Text: "refresh the auth token", Files: []string{"pkg/auth/token.go"}}, 400)
	if !strings.Contains(cond, "pkg/auth/token.go") {
		t.Errorf("query-relevant fact was not promoted into the block:\n%s", cond)
	}
	iAuth := strings.Index(cond, "pkg/auth/token.go")
	iOther := strings.Index(cond, "pkg/render/a.go")
	if iOther >= 0 && iOther < iAuth {
		t.Errorf("irrelevant fact rendered before the relevant one:\n%s", cond)
	}

	// Ordering, not filtering: a fact that matches nothing is still a fact
	// about this project, and a query sharing no tokens with the store must not
	// empty the block.
	if got := f.RenderFor(Query{Text: "zzzq qqzz"}, 400); got != plain {
		t.Errorf("a non-matching query changed the block:\n got %q\nwant %q", got, plain)
	}
}

// TestRenderForWithoutQueryIsByteIdenticalToRender pins the compatibility
// promise: the conditioning is additive, so every existing caller and every
// existing golden output is unaffected.
func TestRenderForWithoutQueryIsByteIdenticalToRender(t *testing.T) {
	f := seedFactsForRender(t)
	f.Observe(Fact{Kind: FactCommand, Subject: "go test", Text: "`go test ./...` works here (3/3 runs succeeded)"})

	base := f.Render(400)
	if base == "" {
		t.Fatal("populated store rendered nothing")
	}
	for _, q := range []Query{
		{},
		{Text: "   "},
		{Text: "the and of a"}, // stopwords only: tokenizes to nothing
		{Language: "go", Model: "qwen2.5-coder", SuccessOnly: true},
	} {
		if got := f.RenderFor(q, 400); got != base {
			t.Errorf("RenderFor(%+v) diverged from Render:\n got %q\nwant %q", q, got, base)
		}
	}

	// The literal shape callers and prompt templates depend on.
	if !strings.HasPrefix(base, "## What we know about this project\n\nCommands that work:\n- `go test ./...`") {
		t.Errorf("heading/action-first order changed:\n%s", base)
	}
	if !strings.HasSuffix(base, "\n") || strings.HasSuffix(base, "\n\n") {
		t.Errorf("trailing newline handling changed: %q", base[len(base)-4:])
	}
}

func TestRenderForRespectsTheTokenBudget(t *testing.T) {
	f := openFacts("", 0, nil, nil)
	for i := 0; i < 40; i++ {
		p := "pkg/auth/token" + itoa(i) + ".go"
		f.Observe(Fact{Kind: FactFile, Subject: p, Text: "`" + p + "` holds auth token refresh logic and changed a lot"})
	}
	q := Query{Text: "auth token refresh logic", Files: []string{"pkg/auth/token1.go"}}
	for _, budget := range []int{40, 120, 400} {
		out := f.RenderFor(q, budget)
		if n := countTokens(nil, out); n > budget {
			t.Errorf("budget %d: render used %d tokens", budget, n)
		}
	}
}
